//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol_web2
{
    using System;
    using System.Collections.Generic;
    
    public partial class meldunki_wady_nn
    {
        public int id { get; set; }
        public int id_meldunek { get; set; }
        public int id_zlecenie { get; set; }
        public int id_wada_nn { get; set; }
        public int ilosc { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
