//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol_web2
{
    using System;
    using System.Collections.Generic;
    
    public partial class meldunki
    {
        public int id { get; set; }
        public int id_zlecenie { get; set; }
        public int id_operator { get; set; }
        public int id_brygadzista { get; set; }
        public int zmiana { get; set; }
        public System.DateTime data_meldunku { get; set; }
        public int ilosc { get; set; }
        public int ilosc_techn { get; set; }
        public System.TimeSpan godz_spr_wtr { get; set; }
        public int wynik_spr_wtr { get; set; }
        public int wyglad_zew { get; set; }
        public int wyglad_grzejnika { get; set; }
        public int przeglad_codz_masz { get; set; }
        public string uwagi { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
