//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol_web2
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatorzy_maszyn
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public bool aktywny { get; set; }
        public int brygada { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
