//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol_web2
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlecenia_produkcyjne
    {
        public int id { get; set; }
        public int wyrob_kod_id { get; set; }
        public string wyrob_kod { get; set; }
        public string wyrob_kod_indeks { get; set; }
        public string wyrob_kod_opis { get; set; }
        public int wyrob_typ { get; set; }
        public int wyrob_il_w_op_zb { get; set; }
        public int wyrob_waga_op { get; set; }
        public int wyrob_waga_1szt { get; set; }
        public int wyrob_zakres_sdr { get; set; }
        public Nullable<int> wyrob_zast_zaworu { get; set; }
        public Nullable<int> wyrob_rodzaj_drutu { get; set; }
        public int wyrob_norma { get; set; }
        public int wyrob_il_w_partii { get; set; }
        public int zlecenie_nr_maszyny { get; set; }
        public int zlecenie_ilosc { get; set; }
        public System.DateTime zlecenie_data_rozp { get; set; }
        public System.DateTime zlecenie_data_zak { get; set; }
        public string zlecenie_nr_partii_surowca { get; set; }
        public string zlecenie_nr_partii_drutu { get; set; }
        public int itf_kategoria { get; set; }
        public int itf_znak1 { get; set; }
        public int itf_znak2 { get; set; }
        public int itf_icc { get; set; }
        public int itf_cc1 { get; set; }
        public int itf_cc2 { get; set; }
        public int itf_smin { get; set; }
        public int itf_smax { get; set; }
        public int itf_trn { get; set; }
        public string itf_prn { get; set; }
        public decimal itf_rez { get; set; }
        public int itf_odch { get; set; }
        public string itf_cz1 { get; set; }
        public string itf_cz2 { get; set; }
        public string itf_ke { get; set; }
        public int trace_znak1 { get; set; }
        public int trace_znak2 { get; set; }
        public int trace_kategoria { get; set; }
        public int trace_smin { get; set; }
        public int trace_smax { get; set; }
        public string trace_partia { get; set; }
        public int trace_producent { get; set; }
        public int trace_sdr { get; set; }
        public int trace_pe_m { get; set; }
        public int trace_material { get; set; }
        public int trace_pe_o { get; set; }
        public int trace_mfr { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
